# Generated by Django 3.2.9 on 2022-12-05 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='slug',
            field=models.SlugField(default=uuid.UUID('56c13abb-74c6-11ed-b2d0-5c80b6f716a0'), max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=uuid.UUID('56c0ec8d-74c6-11ed-ac5d-5c80b6f716a0'), max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(default=uuid.UUID('56c0ec8e-74c6-11ed-868d-5c80b6f716a0'), max_length=200),
        ),
    ]
