# Generated by Django 3.2.9 on 2022-12-08 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0002_auto_20221205_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='slug',
            field=models.SlugField(default=uuid.UUID('482fc9b0-7714-11ed-b238-5c80b6f716a0'), max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=uuid.UUID('482e909a-7714-11ed-bfb4-5c80b6f716a0'), max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(default=uuid.UUID('482e909b-7714-11ed-b334-5c80b6f716a0'), max_length=200),
        ),
    ]
