# Generated by Django 3.2.9 on 2022-12-08 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0003_auto_20221208_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3e9075b9-7749-11ed-b287-5c80b6f716a0'), max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3e8fd975-7749-11ed-8841-5c80b6f716a0'), max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3e900080-7749-11ed-9b2e-5c80b6f716a0'), max_length=200),
        ),
    ]
