# Generated by Django 3.2.9 on 2022-12-05 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=uuid.UUID('56c1d6ea-74c6-11ed-9ed8-5c80b6f716a0'), max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default=uuid.UUID('56c1d6ec-74c6-11ed-978a-5c80b6f716a0'), max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=uuid.UUID('56c1d6eb-74c6-11ed-a7fd-5c80b6f716a0'), max_length=20),
        ),
    ]
