# Generated by Django 3.2.9 on 2022-12-08 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20221205_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=uuid.UUID('483101fd-7714-11ed-94fe-5c80b6f716a0'), max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default=uuid.UUID('483101ff-7714-11ed-87f8-5c80b6f716a0'), max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=uuid.UUID('483101fe-7714-11ed-aba5-5c80b6f716a0'), max_length=20),
        ),
    ]
