# Generated by Django 3.2.9 on 2022-12-08 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20221208_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=uuid.UUID('3e916016-7749-11ed-8b66-5c80b6f716a0'), max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default=uuid.UUID('3e916018-7749-11ed-a5d5-5c80b6f716a0'), max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=uuid.UUID('3e916017-7749-11ed-ba6a-5c80b6f716a0'), max_length=20),
        ),
    ]
